services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: rapsylastic
    healthcheck:
        test: curl -k -u elastic:${ELASTIC_PASSWORD} --silent --fail localhost:9200/_cluster/health || exit 1
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      - node.name=rapsylastic
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

    ports:
      - 9200:9200
    networks:
        - rapsylastic_net
    volumes:
        - rapsylastic_data:/usr/share/elasticsearch/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: rapsylastic_cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    networks:
      - rapsylastic_net
    restart: always 

volumes:
  rapsylastic_data:

networks:
  rapsylastic_net:
    driver: bridge
